### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [stylewarning/cl-permutation#17]
Building with SBCL 2.1.10 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 7d441be7ab47777516512abe993e6dffcee8478e

*cl-permutation-examples* fails to build because of a failure in  _cl-permutation_.

*cl-permutation-tests* fails to build because of a failure in  _cl-permutation_.

*cl-permutation* fails to build with the following error:

```
; caught WARNING:
;   * is not permitted as an argument to the FUNCTION type specifier
; 
; caught WARNING:
;   * is not permitted as an argument to the FUNCTION type specifier
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001C08103}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "cl-permutation" "minkwitz">

```

[Full log here](http://report.quicklisp.org/2021-11-02/failure-report/cl-permutation.html)

**Comment by stylewarning** [comment]
Fixed in 20c10e9
